spring:
  # mysql5.7数据库配置
  #已经修改乘8.X
  datasource:
    #    url: jdbc:mysql://localhost:3306/my_mall?useSSL=true&useUnicode=true&characterEncoding=utf8
#    url: jdbc:mysql://8.138.133.94:3306/keshe?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    url: jdbc:postgresql://og.segfault.pp.ua:8887/prj
    username: admin
    password: wkTeam@666
    driver-class-name: org.postgresql.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource



server:
  # 访问端口
  port: 8083
  # 访问根路径
  servlet:
    context-path: /scientific-manage

# 配置MyBatis的mapper.xml的路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
#MyBatis的mapper语句的输出
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置日志输出(当前配置的是默认的控制台输出)
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
